services:
  sublinkx:
    image: ghcr.io/wangxvwei/sublinkx:latest
    container_name: sublinkx
    ports:
      - "8000:8000"
    volumes:
      - ./db:/app/db
      - ./template:/app/template
      - ./logs:/app/logs
    environment:
      TZ: Asia/Shanghai
      UPDATE_REPO: wangxvwei/sublinkX
      DOCKER_IMAGE: ghcr.io/wangxvwei/sublinkx
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  watchtower:
    image: containrrr/watchtower:latest
    container_name: sublinkx-watchtower
    profiles:
      - auto-update
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --cleanup
      - --label-enable
      - --interval
      - "3600"
    restart: unless-stopped
